<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $template->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1e293b; margin: 32px; }
        h1 { font-size: 18px; margin: 0 0 2px; }
        .meta { color: #64748b; font-size: 11px; margin-bottom: 18px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th, td { text-align: left; padding: 7px 10px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        th { width: 35%; color: #64748b; font-weight: 600; }
        .signature { margin-top: 28px; padding: 14px 16px; border: 1px solid #e2e8f0; border-radius: 6px; }
        .signature .name { font-size: 15px; font-weight: 700; font-style: italic; }
        .signature .detail { color: #64748b; font-size: 11px; margin-top: 4px; }
        .footer { margin-top: 32px; color: #94a3b8; font-size: 10px; }
    </style>
</head>
<body>
    <h1>{{ $template->name }}</h1>
    <p class="meta">
        {{ $template->targetLabel() }}: {{ $subjectName }}
        · Submission #{{ $submission->id }}
        · {{ $submission->created_at?->format('M j, Y') }}
    </p>

    <table>
        @foreach($fields ?? ($template->fields ?? []) as $field)
            <tr>
                <th>{{ $field['label'] ?? $field['key'] }}</th>
                <td>{{ $values[$field['key'] ?? ''] ?? '—' }}</td>
            </tr>
        @endforeach
    </table>

    <div class="signature">
        @php
            $ink = $submission->signature_image
                ?: data_get($submission->field_values, 'signature_image');
        @endphp
        @if($ink)
            <div style="margin-bottom: 8px;">
                <img src="{{ $ink }}" alt="Signature" style="max-width: 280px; max-height: 90px;">
            </div>
        @endif
        <div class="name">{{ $submission->signed_by_name }}</div>
        <div class="detail">
            Electronically signed {{ $submission->signed_at?->format('M j, Y g:i A') }}
            · This document is locked and cannot be edited.
        </div>
    </div>

    <p class="footer">
        Generated by {{ config('app.name') }} · {{ now()->format('M j, Y g:i A') }}
    </p>
</body>
</html>
