<?php

return [

    'categories' => [
        'financial' => [
            'label' => 'Financial',
            'icon' => '💵',
            'tone' => 'fin',
        ],
        'operational' => [
            'label' => 'Operational',
            'icon' => '📊',
            'tone' => 'ops',
        ],
        'compliance' => [
            'label' => 'Compliance',
            'icon' => '🗂',
            'tone' => 'comp',
        ],
        'caregiver_hr' => [
            'label' => 'Caregiver / HR',
            'icon' => '🧑‍⚕️',
            'tone' => 'hr',
        ],
        'ai_performance' => [
            'label' => 'AI Performance',
            'icon' => '🤖',
            'tone' => 'ai',
        ],
        'custom' => [
            'label' => 'Custom',
            'icon' => '⚙️',
            'tone' => 'cust',
        ],
    ],

    'period_presets' => [
        'month' => 'Month',
        'quarter' => 'Quarter',
        'ytd' => 'YTD',
        'trailing_12' => 'Trailing 12mo',
    ],

    'reports' => [
        // ── Financial (9) ───────────────────────────────────────────────
        'revenue-collections' => [
            'category' => 'financial',
            'name' => 'Revenue & Collections',
            'icon' => '💵',
            'description' => 'Billed, collected, outstanding by program & month',
            'schedule' => 'monthly',
            'view' => 'revenue-collections',
        ],
        'ar-aging' => [
            'category' => 'financial',
            'name' => 'AR Aging',
            'icon' => '📉',
            'description' => 'Outstanding receivables by age & payer',
            'schedule' => 'weekly',
            'view' => 'ar-aging',
        ],
        'margin-by-program' => [
            'category' => 'financial',
            'name' => 'Margin by Program',
            'icon' => '⚖️',
            'description' => 'Billing rate vs caregiver wage · MICH vs DHS',
            'schedule' => 'on_demand',
            'view' => 'margin-by-program',
        ],
        'payroll-summary' => [
            'category' => 'financial',
            'name' => 'Payroll Summary',
            'icon' => '🧾',
            'description' => 'Gross by caregiver, hours, grace holds',
            'schedule' => 'per_run',
            'view' => 'payroll-summary',
        ],
        'denials-rejections' => [
            'category' => 'financial',
            'name' => 'Denials & Rejections',
            'icon' => '🚫',
            'description' => 'Rejected claims, reasons, rework status',
            'schedule' => 'on_demand',
            'view' => 'denials-rejections',
        ],
        'payer-mix' => [
            'category' => 'financial',
            'name' => 'Payer Mix',
            'icon' => '🏦',
            'description' => 'Revenue distribution by payer and MCO',
            'schedule' => 'monthly',
            'view' => 'payer-mix',
        ],
        'collections-forecast' => [
            'category' => 'financial',
            'name' => 'Collections Forecast',
            'icon' => '📈',
            'description' => 'Projected collections from in-flight claims',
            'schedule' => 'weekly',
            'view' => 'collections-forecast',
        ],
        'billing-productivity' => [
            'category' => 'financial',
            'name' => 'Billing Productivity',
            'icon' => '⚡',
            'description' => 'Claims submitted, clean-rate, and cycle time',
            'schedule' => 'monthly',
            'view' => 'billing-productivity',
        ],
        'cash-position' => [
            'category' => 'financial',
            'name' => 'Cash Position',
            'icon' => '💰',
            'description' => 'Billed vs payroll vs net cash for the period',
            'schedule' => 'monthly',
            'view' => 'cash-position',
        ],

        // ── Operational (7) ─────────────────────────────────────────────
        'census-utilization' => [
            'category' => 'operational',
            'name' => 'Census & Caregiver Utilization',
            'icon' => '👥',
            'description' => 'Active clients, intakes/discharges, caregiver load',
            'schedule' => 'monthly',
            'view' => 'census-utilization',
        ],
        'visit-completion' => [
            'category' => 'operational',
            'name' => 'Visit Completion',
            'icon' => '✓',
            'description' => 'Completed, missed, and cancelled visits',
            'schedule' => 'weekly',
            'view' => 'visit-completion',
        ],
        'authorization-utilization' => [
            'category' => 'operational',
            'name' => 'Authorization Utilization',
            'icon' => '📜',
            'description' => 'Authorized vs billed hours by client',
            'schedule' => 'monthly',
            'view' => 'authorization-utilization',
        ],
        'intake-pipeline' => [
            'category' => 'operational',
            'name' => 'Intake Pipeline',
            'icon' => '📥',
            'description' => 'New leads, conversions, and pending intakes',
            'schedule' => 'weekly',
            'view' => 'intake-pipeline',
        ],
        'schedule-adherence' => [
            'category' => 'operational',
            'name' => 'Schedule Adherence',
            'icon' => '📅',
            'description' => 'On-time clock-in/out and EVV compliance',
            'schedule' => 'monthly',
            'view' => 'schedule-adherence',
        ],
        'evv-compliance' => [
            'category' => 'operational',
            'name' => 'EVV Compliance',
            'icon' => '📍',
            'description' => 'GPS-verified visits and exemption tracking',
            'schedule' => 'monthly',
            'view' => 'evv-compliance',
        ],
        'workflow-throughput' => [
            'category' => 'operational',
            'name' => 'Workflow Throughput',
            'icon' => '⚙️',
            'description' => 'Queue volume and resolution time by type',
            'schedule' => 'weekly',
            'view' => 'workflow-throughput',
        ],

        // ── Compliance (6) ────────────────────────────────────────────
        'compliance-authorizations' => [
            'category' => 'compliance',
            'name' => 'Compliance & Authorizations',
            'icon' => '🗂',
            'description' => 'Monthly forms, HHAeX verification, PA status',
            'schedule' => 'monthly',
            'view' => 'compliance-authorizations',
        ],
        'forms-timeliness' => [
            'category' => 'compliance',
            'name' => 'Forms Timeliness',
            'icon' => '📋',
            'description' => 'On-time vs late monthly compliance forms',
            'schedule' => 'monthly',
            'view' => 'forms-timeliness',
        ],
        'background-monitoring' => [
            'category' => 'compliance',
            'name' => 'Background Monitoring',
            'icon' => '🛡',
            'description' => 'CHAMPS, ICHAT, SAM/OIG currency',
            'schedule' => 'weekly',
            'view' => 'background-monitoring',
        ],
        'document-verification' => [
            'category' => 'compliance',
            'name' => 'Document Verification',
            'icon' => '📄',
            'description' => 'Verified vs pending document status',
            'schedule' => 'monthly',
            'view' => 'document-verification',
        ],
        'hha-exchange-match' => [
            'category' => 'compliance',
            'name' => 'HHAeXchange Match',
            'icon' => '🔄',
            'description' => 'EVV hours matched to HHAeXchange',
            'schedule' => 'monthly',
            'view' => 'hha-exchange-match',
        ],
        'service-stop-risk' => [
            'category' => 'compliance',
            'name' => 'Service-Stop Risk',
            'icon' => '⚠️',
            'description' => 'Clients at risk from unrenewed authorizations',
            'schedule' => 'weekly',
            'view' => 'service-stop-risk',
        ],

        // ── Caregiver / HR (5) ──────────────────────────────────────────
        'workforce' => [
            'category' => 'caregiver_hr',
            'name' => 'Workforce Report',
            'icon' => '🧑‍⚕️',
            'description' => 'Roster mix, onboarding, background status, turnover',
            'schedule' => 'monthly',
            'view' => 'workforce',
        ],
        'onboarding-pipeline' => [
            'category' => 'caregiver_hr',
            'name' => 'Onboarding Pipeline',
            'icon' => '🚀',
            'description' => 'Caregivers in CHAMPS/ICHAT onboarding',
            'schedule' => 'weekly',
            'view' => 'onboarding-pipeline',
        ],
        'turnover-analysis' => [
            'category' => 'caregiver_hr',
            'name' => 'Turnover Analysis',
            'icon' => '📉',
            'description' => 'Trailing-twelve-month caregiver turnover',
            'schedule' => 'quarterly',
            'view' => 'turnover-analysis',
        ],
        'live-in-roster' => [
            'category' => 'caregiver_hr',
            'name' => 'Live-in Roster',
            'icon' => '🏠',
            'description' => 'EVV-exempt live-in caregivers on file',
            'schedule' => 'monthly',
            'view' => 'live-in-roster',
        ],
        'wage-compliance' => [
            'category' => 'caregiver_hr',
            'name' => 'Wage Compliance',
            'icon' => '💵',
            'description' => 'Hourly wage vs agency minimums',
            'schedule' => 'monthly',
            'view' => 'wage-compliance',
        ],

        // ── AI Performance (4) ──────────────────────────────────────────
        'ai-agent-performance' => [
            'category' => 'ai_performance',
            'name' => 'AI Agent Performance',
            'icon' => '🤖',
            'description' => 'Automation rate, miss-rate, escalations by agent',
            'schedule' => 'monthly',
            'view' => 'ai-agent-performance',
        ],
        'escalation-volume' => [
            'category' => 'ai_performance',
            'name' => 'Escalation Volume',
            'icon' => '⬆️',
            'description' => 'Tasks escalated from agents to staff',
            'schedule' => 'weekly',
            'view' => 'escalation-volume',
        ],
        'approval-turnaround' => [
            'category' => 'ai_performance',
            'name' => 'Approval Turnaround',
            'icon' => '⏱',
            'description' => 'Time from queue to approval decision',
            'schedule' => 'monthly',
            'view' => 'approval-turnaround',
        ],
        'hours-saved' => [
            'category' => 'ai_performance',
            'name' => 'Hours Saved',
            'icon' => '⏰',
            'description' => 'Estimated manual hours avoided by automation',
            'schedule' => 'monthly',
            'view' => 'hours-saved',
        ],

        // ── Custom ────────────────────────────────────────────────────
        'custom-builder' => [
            'category' => 'custom',
            'name' => 'Report Builder',
            'icon' => '✨',
            'description' => 'Build a report in plain language or pick fields',
            'schedule' => 'on_demand',
            'view' => 'custom-builder',
        ],
    ],

    'schedule_labels' => [
        'monthly' => 'Monthly',
        'weekly' => 'Weekly',
        'quarterly' => 'Quarterly',
        'per_run' => 'Per run',
        'on_demand' => 'On demand',
    ],

    'ai_agents' => [
        ['slug' => 'billing', 'name' => 'Billing agent (CP-01 + claims)'],
        ['slug' => 'compliance', 'name' => 'Compliance / wellness-call agent'],
        ['slug' => 'payroll', 'name' => 'Payroll agent'],
        ['slug' => 'background', 'name' => 'Background-check agent (RPA)'],
        ['slug' => 'authorizations', 'name' => 'Authorizations / renewal agent'],
    ],

];
