<?php

return [

    'miss_rate_ceiling' => 2.0,

    'autonomy_modes' => [
        'autonomous' => 'Autonomous',
        'approval_required' => 'Approval-required',
        'monitor_only' => 'Monitor-only',
    ],

    'autonomy_labels' => [
        'autonomous' => 'Autonomous',
        'approval_to_activate' => 'Approval to activate',
        'approval_to_submit' => 'Approval to submit',
        'approval_to_release' => 'Approval to release',
        'autonomous_flag' => 'Autonomous · flag to approve',
    ],

    'fleet' => [
        'uptime_pct' => 99.9,
        'tasks_today' => 214,
        'tasks_today_auto_pct' => 96,
        'automation_rate_pct' => 96,
        'fleet_miss_rate_pct' => 0.7,
        'awaiting_approval' => 7,
        'open_alerts' => 1,
        'hrs_saved_est' => 410,
        'miss_rate_weeks' => [0.7, 0.8, 0.6, 0.9, 0.7, 0.8, 0.6, 0.8, 0.6, 0.7, 0.8, 0.7],
    ],

    'alerts' => [
        [
            'tone' => 'esc',
            'title' => 'Authorizations agent at 1.6% miss-rate',
            'detail' => 'on watch (under 2%)',
            'time' => 'flagged Jun 1 · monitoring',
        ],
        [
            'tone' => 'now',
            'title' => '7 items awaiting your approval',
            'detail' => 'across 3 agents',
            'time' => 'live · open queue',
            'link' => '/workflow-queues',
        ],
        [
            'tone' => 'ok',
            'title' => 'Background batch completed',
            'detail' => '138/138 clear',
            'time' => 'Jun 1 · 2:00a',
        ],
        [
            'tone' => 'ok',
            'title' => 'Availity connection check passed',
            'detail' => null,
            'time' => 'Jun 2 · 6:00a',
        ],
        [
            'tone' => 'ok',
            'title' => 'Payroll batch scheduled',
            'detail' => 'Tue Jun 2 → Fri Jun 5',
            'time' => 'queued',
        ],
    ],

    'agents' => [
        'intake' => [
            'slug' => 'intake',
            'name' => 'Intake Agent',
            'short_name' => 'Intake',
            'role' => 'Referral → eligibility → build chart',
            'icon' => '📝',
            'icon_bg' => 'bg-[#dbeafe]',
            'autonomy' => 'approval_to_activate',
            'autonomy_mode' => 'approval_required',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 96,
            'auto_handled_pct' => 94,
            'escalated' => 6,
            'miss_rate_pct' => 0.6,
            'last_run' => 'Last run · 2h ago',
            'summary' => 'Referral intake → eligibility → chart build · miss-rate 0.6%',
            'what_it_does' => [
                'Function' => 'Processes new referrals through eligibility and builds the client chart',
                'Runs the gate' => 'Eligibility verification before chart activation',
                'Reads from' => 'Referrals · Directories · Authorizations',
                'Writes to' => 'Clients · Workflow Queues · Documents',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [],
            'run_log' => [],
            'linked' => [
                ['label' => 'Clients', 'route' => 'clients.index'],
                ['label' => 'Approval queue', 'url' => '/workflow-queues'],
            ],
        ],
        'authorizations' => [
            'slug' => 'authorizations',
            'name' => 'Authorizations & Renewal Agent',
            'short_name' => 'Authorizations & Renewal',
            'role' => 'PA renewals · Time/Task reassessment',
            'icon' => '📜',
            'icon_bg' => 'bg-[#ede9fe]',
            'autonomy' => 'approval_to_submit',
            'autonomy_mode' => 'approval_required',
            'status' => 'on_watch',
            'on_watch' => true,
            'paused' => false,
            'tasks_may' => 134,
            'auto_handled_pct' => 91,
            'escalated' => 13,
            'miss_rate_pct' => 1.6,
            'last_run' => 'On watch',
            'summary' => 'PA renewals · Time/Task reassessment · miss-rate 1.6%',
            'what_it_does' => [
                'Function' => 'Tracks PA expirations and submits renewal packets',
                'Runs the gate' => 'Authorization window and unit caps before submit',
                'Reads from' => 'Authorizations · Clients · Compliance forms',
                'Writes to' => 'Authorizations · Workflow Queues · Documents',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => true,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [],
            'run_log' => [],
            'linked' => [
                ['label' => 'Authorizations', 'url' => '/authorizations'],
                ['label' => 'Approval queue', 'url' => '/workflow-queues'],
            ],
        ],
        'compliance' => [
            'slug' => 'compliance',
            'name' => 'Compliance & Wellness-Call Agent (VA)',
            'short_name' => 'Compliance / Wellness',
            'role' => 'Monthly calls · forms · concern notes',
            'icon' => '📞',
            'icon_bg' => 'bg-[#d1fae5]',
            'autonomy' => 'autonomous',
            'autonomy_mode' => 'autonomous',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 276,
            'auto_handled_pct' => 95,
            'escalated' => 14,
            'miss_rate_pct' => 0.9,
            'last_run' => 'Last run · 14m ago',
            'summary' => 'Monthly wellness calls · forms · concern notes · miss-rate 0.9%',
            'what_it_does' => [
                'Function' => 'Runs monthly wellness calls and files compliance forms',
                'Runs the gate' => 'Call completion and form signature before close',
                'Reads from' => 'Clients · Schedule · Compliance templates',
                'Writes to' => 'Compliance & Documents · Communications',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [],
            'run_log' => [],
            'linked' => [
                ['label' => 'Compliance & Documents', 'route' => 'compliance'],
            ],
        ],
        'billing' => [
            'slug' => 'billing',
            'name' => 'Billing Agent',
            'short_name' => 'Billing',
            'role' => 'CP-01 gate · 837P / Home Help · submit',
            'icon' => '💵',
            'icon_bg' => 'bg-[#e0f2fe]',
            'autonomy' => 'autonomous',
            'autonomy_mode' => 'autonomous',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 412,
            'auto_handled_pct' => 97,
            'escalated' => 12,
            'miss_rate_pct' => 0.5,
            'last_run' => 'Last run · 31m ago',
            'summary' => 'CP-01 pre-billing gate → generate 837P / Home Help Invoice → submit · miss-rate 0.5%',
            'what_it_does' => [
                'Function' => 'Generates & submits this month\'s bill on compliance-form receipt',
                'Runs the gate' => 'CP-01 — verifies last month paid, no balance; catches silent closures',
                'MICH path' => 'EDI 837P (T1019) → Availity',
                'DHS path' => 'Home Help Invoice → email/eFax to ASW',
                'Reads from' => 'Compliance forms · Authorizations · Directories (rate/channel)',
                'Writes to' => 'Billing & Claims · Documents (7-yr)',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => true,
                'approval_threshold' => 5000,
            ],
            'connected_systems' => [
                ['name' => 'Availity (837P)', 'status' => 'OK'],
                ['name' => 'UnitedHealthcare EDI', 'status' => 'OK'],
                ['name' => 'Email / eFax (ASW)', 'status' => 'OK'],
            ],
            'run_log' => [
                ['tone' => 'ok', 'title' => 'Submitted 837P — Maria Hassan', 'detail' => '$3,240 · CP-01 passed', 'time' => 'May 31 · 9:12a'],
                ['tone' => 'esc', 'title' => 'Held — Hisham Abboud', 'detail' => 'CP-01 fail (Apr unpaid) → your queue', 'time' => 'May 31 · 9:10a'],
                ['tone' => 'ok', 'title' => 'Emailed Home Help Invoice — Khalil Ahmed', 'detail' => '$2,484 → ASW', 'time' => 'May 31 · 9:04a'],
                ['tone' => 'esc', 'title' => 'Escalated — Robert Davis', 'detail' => 'rejection (member-ID) needs review', 'time' => 'May 30 · 4:22p'],
            ],
            'linked' => [
                ['label' => 'Billing & Claims', 'route' => 'billing-claims-audit.index'],
                ['label' => 'Approval queue', 'url' => '/workflow-queues'],
                ['label' => 'AI Performance report', 'route' => 'reports.show', 'params' => ['report' => 'ai-agent-performance']],
            ],
        ],
        'payroll' => [
            'slug' => 'payroll',
            'name' => 'Payroll Agent',
            'short_name' => 'Payroll',
            'role' => 'Grace window · batch build · AccountantsWorld',
            'icon' => '💰',
            'icon_bg' => 'bg-[#fce7f3]',
            'autonomy' => 'approval_to_release',
            'autonomy_mode' => 'approval_required',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 168,
            'auto_handled_pct' => 98,
            'escalated' => 4,
            'miss_rate_pct' => 0.3,
            'last_run' => 'Next run · Tue Jun 2',
            'summary' => 'Grace window · batch build · AccountantsWorld · miss-rate 0.3%',
            'what_it_does' => [
                'Function' => 'Builds payroll batches after grace window and submits to AccountantsWorld',
                'Runs the gate' => 'Grace period and hold checks before release',
                'Reads from' => 'Payroll · Schedule · EVV',
                'Writes to' => 'Payroll · Documents',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [
                ['name' => 'AccountantsWorld', 'status' => 'OK'],
            ],
            'run_log' => [],
            'linked' => [
                ['label' => 'Payroll', 'route' => 'payroll.index'],
                ['label' => 'Approval queue', 'url' => '/workflow-queues'],
            ],
        ],
        'background' => [
            'slug' => 'background',
            'name' => 'Background-Check Agent (RPA)',
            'short_name' => 'Background-check (RPA)',
            'role' => 'CHAMPS · ICHAT · SAM · OIG',
            'icon' => '🛡',
            'icon_bg' => 'bg-[#fef3c7]',
            'autonomy' => 'autonomous_flag',
            'autonomy_mode' => 'autonomous',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 180,
            'auto_handled_pct' => 96,
            'escalated' => 9,
            'miss_rate_pct' => 1.1,
            'last_run' => 'Last batch · Jun 1',
            'summary' => 'CHAMPS · ICHAT · SAM · OIG batch checks · miss-rate 1.1%',
            'what_it_does' => [
                'Function' => 'Runs exclusion and background checks via state portals',
                'Runs the gate' => 'Clearance required before caregiver activation',
                'Reads from' => 'Caregivers · Credential Vault',
                'Writes to' => 'Background Checks · Documents',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [
                ['name' => 'CHAMPS · ICHAT (RPA)', 'status' => 'OK'],
                ['name' => 'SAM.gov · OIG LEIE', 'status' => 'OK'],
            ],
            'run_log' => [],
            'linked' => [
                ['label' => 'Background Checks', 'url' => '/background-checks'],
            ],
        ],
        'communications' => [
            'slug' => 'communications',
            'name' => 'Communications Agent',
            'short_name' => 'Communications',
            'role' => 'Calls · SMS · email · eFax triage (AR+EN)',
            'icon' => '💬',
            'icon_bg' => 'bg-[#e0e7ff]',
            'autonomy' => 'autonomous',
            'autonomy_mode' => 'autonomous',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 1284,
            'auto_handled_pct' => 96,
            'escalated' => 52,
            'miss_rate_pct' => 0.4,
            'last_run' => 'Last run · 3m ago',
            'summary' => 'Calls · SMS · email · eFax triage · miss-rate 0.4%',
            'what_it_does' => [
                'Function' => 'Triages inbound/outbound communications across channels',
                'Runs the gate' => 'PHI and escalation rules before auto-reply',
                'Reads from' => 'RingCentral · Clients · Caregivers',
                'Writes to' => 'Communications · Workflow Queues',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [
                ['name' => 'RingCentral', 'status' => 'OK'],
            ],
            'run_log' => [],
            'linked' => [
                ['label' => 'Communications', 'route' => 'communications.index'],
            ],
        ],
        'evv' => [
            'slug' => 'evv',
            'name' => 'Visit/EVV Monitor Agent',
            'short_name' => 'EVV',
            'role' => 'Watch visits · flag EVV issues · mark no-shows',
            'icon' => '📍',
            'icon_bg' => 'bg-[#dcfce7]',
            'autonomy' => 'autonomous_flag',
            'autonomy_mode' => 'autonomous',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 180,
            'auto_handled_pct' => 92,
            'escalated' => 14,
            'miss_rate_pct' => 0.5,
            'last_run' => 'Last run · live',
            'summary' => 'Monitors clock-in/out · location match · billable gate · miss-rate 0.5%',
            'what_it_does' => [
                'Function' => 'Watches every care visit live and flags EVV problems for humans',
                'Runs the gate' => 'Only clean complete visits become billable',
                'Reads from' => 'Schedule · Visit Reports · Clients (home GPS)',
                'Writes to' => 'Visit Reports · Tasks · Workflow Queues',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [
                ['name' => 'HHAeXchange', 'status' => 'OK'],
            ],
            'run_log' => [],
            'linked' => [
                ['label' => 'Visit Reports', 'route' => 'visit-reports'],
            ],
        ],
        'forms' => [
            'slug' => 'forms',
            'name' => 'Forms / Documentation Agent',
            'short_name' => 'Forms',
            'role' => 'Pre-fill forms · send for e-sign · file PDFs',
            'icon' => '📄',
            'icon_bg' => 'bg-[#fef3c7]',
            'autonomy' => 'approval_to_submit',
            'autonomy_mode' => 'approval_required',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 74,
            'auto_handled_pct' => 88,
            'escalated' => 9,
            'miss_rate_pct' => 0.8,
            'last_run' => 'Last run · 1h ago',
            'summary' => 'Pre-fills paperwork · e-sign · files to Documents · miss-rate 0.8%',
            'what_it_does' => [
                'Function' => 'Generates draft forms for the right person and files signed copies',
                'Runs the gate' => 'Signed forms lock; compliance templates update Compliance',
                'Reads from' => 'Clients · Caregivers · Form templates',
                'Writes to' => 'Forms · Documents · Compliance',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [
                ['name' => 'DocuSign', 'status' => 'Configured'],
            ],
            'run_log' => [],
            'linked' => [
                ['label' => 'Forms', 'route' => 'forms'],
            ],
        ],
        'document' => [
            'slug' => 'document',
            'name' => 'Document Agent',
            'short_name' => 'Document',
            'role' => 'Filing · OCR · 7-yr retention',
            'icon' => '🗂',
            'icon_bg' => 'bg-[#f1f5f9]',
            'autonomy' => 'autonomous',
            'autonomy_mode' => 'autonomous',
            'status' => 'healthy',
            'on_watch' => false,
            'paused' => false,
            'tasks_may' => 503,
            'auto_handled_pct' => 99,
            'escalated' => 5,
            'miss_rate_pct' => 0.2,
            'last_run' => 'Last run · 8m ago',
            'summary' => 'Filing · OCR · 7-yr retention · miss-rate 0.2%',
            'what_it_does' => [
                'Function' => 'Files, OCRs, and retains documents per HIPAA policy',
                'Runs the gate' => 'Retention and classification before archive',
                'Reads from' => 'All modules · Uploads',
                'Writes to' => 'Compliance & Documents · Archive',
            ],
            'guardrails' => [
                'hold_on_gate_fail' => true,
                'auto_resubmit' => false,
                'approval_threshold' => 0,
            ],
            'connected_systems' => [
                ['name' => 'Google Workspace', 'status' => 'OK'],
            ],
            'run_log' => [],
            'linked' => [
                ['label' => 'Compliance & Documents', 'route' => 'compliance'],
            ],
        ],
    ],

];
