name: Deploy Beydountech Staging

concurrency:
  group: staging
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Create Deployment ZIP
        run: |
          zip -r staging-beydountech.zip . \
            -x ".git/*" \
            -x "node_modules/*" \
            -x "vendor/*" \
            -x ".env" \
            -x "storage/*"

      - name: Upload ZIP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_KEY_PASSPHRASE }}
          source: "staging-beydountech.zip"
          target: "/home/beydswaw/public_html/beydountech-stage.zip"

      - name: Run Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_KEY_PASSPHRASE }}
          script: |
            cd /home/beydswaw/public_html/beydountech-stage.zip
            chmod +x deploy.sh
            ./deploy.sh